//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisualStudioInstallerCore {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class InstallerResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InstallerResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VisualStudioInstallerCore.InstallerResources", typeof(InstallerResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        public static string Available {
            get {
                return ResourceManager.GetString("Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual Studio-Support.
        /// </summary>
        public static string Chat_Link_Text {
            get {
                return ResourceManager.GetString("Chat_Link_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat with.
        /// </summary>
        public static string Chat_Text_1 {
            get {
                return ResourceManager.GetString("Chat_Text_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Chat_Text_2 {
            get {
                return ResourceManager.GetString("Chat_Text_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Developer Community.
        /// </summary>
        public static string FAQ_Link_Text {
            get {
                return ResourceManager.GetString("FAQ_Link_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout the.
        /// </summary>
        public static string FAQ_Text_1 {
            get {
                return ResourceManager.GetString("FAQ_Text_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to where developers provide feedback and answers to many common problems..
        /// </summary>
        public static string FAQ_Text_2 {
            get {
                return ResourceManager.GetString("FAQ_Text_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free, fully-featured IDE for students, open-source and individual developers.
        /// </summary>
        public static string Info_Community {
            get {
                return ResourceManager.GetString("Info_Community", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft DevOps solution for productivity and coordination across teams of any size.
        /// </summary>
        public static string Info_Enterprise {
            get {
                return ResourceManager.GetString("Info_Enterprise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professional developer tools and services for small teams.
        /// </summary>
        public static string Info_Professional {
            get {
                return ResourceManager.GetString("Info_Professional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        public static string Install {
            get {
                return ResourceManager.GetString("Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed.
        /// </summary>
        public static string Installed {
            get {
                return ResourceManager.GetString("Installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch.
        /// </summary>
        public static string Launch {
            get {
                return ResourceManager.GetString("Launch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether you&apos;re new to development or an experienced developer, we have you covered with our tutorials, videos, and sample code..
        /// </summary>
        public static string Learn_Text {
            get {
                return ResourceManager.GetString("Learn_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn.
        /// </summary>
        public static string Learn_Title {
            get {
                return ResourceManager.GetString("Learn_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License terms.
        /// </summary>
        public static string License_Terms {
            get {
                return ResourceManager.GetString("License_Terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Visual Studio extensions to add support for new technologies, integrate with other products and services, and fine-tune your experience..
        /// </summary>
        public static string Marketplace_Text {
            get {
                return ResourceManager.GetString("Marketplace_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketplace.
        /// </summary>
        public static string Marketplace_Title {
            get {
                return ResourceManager.GetString("Marketplace_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        public static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need some help?.
        /// </summary>
        public static string NeedHelp_Title {
            get {
                return ResourceManager.GetString("NeedHelp_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release.
        /// </summary>
        public static string Release {
            get {
                return ResourceManager.GetString("Release", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release notes.
        /// </summary>
        public static string ReleaseNotes {
            get {
                return ResourceManager.GetString("ReleaseNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We invite you to go online to hon your skills and find additional tools to support your development workflow..
        /// </summary>
        public static string Welcome_Text {
            get {
                return ResourceManager.GetString("Welcome_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome!.
        /// </summary>
        public static string Welcome_Title {
            get {
                return ResourceManager.GetString("Welcome_Title", resourceCulture);
            }
        }
    }
}
